### ISSUE TITLE
Error when creating package:

### ISSUE THREAD

**Issue by carlosalbaidiada** [MSEndpointMgr/ModernDriverManagement#194]
Hi,

this tool has been working smooth since ever. Now I'm getting and error at the time is creating the package driver.

This is what I get

- ConfigMgr: Creating driver package	DriverAutomationTool	27/09/2022 17:14:44	9628 (0x259C)
======== Errors(s) Occurred ========	DriverAutomationTool	27/09/2022 17:14:44	9628 (0x259C)
[Error] - Not found  System.Management.ManagementException: Not found 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObject.Initialize(Boolean getObject)
   at System.Management.ManagementObject.Put(PutOptions options)
   at Microsoft.ConfigurationManagement.ManagementProvider.WqlQueryEngine.WqlResultObject.Put(ReportProgress progressReport)	DriverAutomationTool	27/09/2022 17:14:44	9628 (0x259C)
 	DriverAutomationTool	27/09/2022 17:14:44	9628 (0x259C)

Fails from diferent computers where DAT is installed.

Thanks in advance

**Comment by chriswhiteIT** [comment]
Did you ever get answers to this? I am getting an error when the tool is attempting to create packages, tool is being ran from a remote server seperate from the SQL / DB server:

[Error] - Not found  System.Management.ManagementException: Not found 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObject.Initialize(Boolean getObject)
   at System.Management.ManagementObject.Put(PutOptions options)
   at Microsoft.ConfigurationManagement.ManagementProvider.WqlQueryEngine.WqlResultObject.Put(ReportProgress progressReport)	DriverAutomationTool	08/08/2023 12:00:21	3040 (0x0BE0)

**Comment by Acabar** [comment]
I'm also seeing this in the logs when trying to pull down some Dell drivers. The download completes, but when trying to create the package I get this.
In my case, the tool is being run directly on the ConfigMgr server.

**Comment by lowg1974** [comment]
Seems SQL 2022 is not yet supported by MECM Current branch.

I had to change the compatibility level of the CM database so that it would import drivers successfully.

Solution was found here: https://www.reddit.com/r/SCCM/comments/zz8uoj/issues_importing_drivers_into_mecm/

Altered the database using following: ALTER DATABASE <CM_DB> SET COMPATIBILITY_LEVEL = 150
