### ISSUE TITLE
'- ConfigMgr: Creating driver package' Fails

### ISSUE THREAD

**Issue by chriswhiteIT** [MSEndpointMgr/ModernDriverManagement#252]
....with the following error from logs:

[Error] - Not found  System.Management.ManagementException: Not found 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObject.Initialize(Boolean getObject)
   at System.Management.ManagementObject.Put(PutOptions options)
   at Microsoft.ConfigurationManagement.ManagementProvider.WqlQueryEngine.WqlResultObject.Put(ReportProgress progressReport)	DriverAutomationTool	08/08/2023 12:00:21	3040 (0x0BE0)

Tool is being ran from remote management server not on the CAS or DB server....

Thanks in advance :)

**Comment by Acabar** [comment]
@chriswhiteIT I'm getting the same error, do you recall what you did to resolve the issue?
